### ISSUE TITLE
Why the sub-typedoc path to typescript module in import?

### ISSUE THREAD

**Issue by nrser** [rbuckton/typedoc-plugin-biblio#1]
I'm referencing this line:

https://github.com/rbuckton/typedoc-plugin-biblio/blob/668203f55e46b3afda070e8a5cd576cb5f5ac38c/src/plugin.ts#L18

I ended up there because it error'd out for me:

```
Error: The plugin ./node_modules/typedoc-plugin-biblio could not be loaded.

Error: Cannot find module 'typedoc/node_modules/typescript/lib/typescript'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (./node_modules/typedoc-plugin-biblio/src/plugin.ts:18:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

This is because my project depends on the `typescript` package, so NPM (well, Yarn, but it *should* behave the same) places `typescript` in the top-level `node_modes` in this case, not under `node_modules/typedoc/node_modules`, where Biblio is looking for it.

Why is that import path constructed like that? I don't think I've ever come across that approach... `typedoc` simply depends on `typescript` from what I can tell (versus vendoring it in some way), so NPM and friends will "lift" it up if the dependency can be shared with other packages, such as in my case.

**Comment by nrser** [comment]
Ok, I'm starting to see the problem... `plugin.ts` needs to load *the* `typescript` package (on a runtime instance-level) that `typedoc` is using so that the types match, but `typedoc-plugin-biblio` at the time of writing was using a more recent version of `typescript` (`^3.4.5`) than the version of `typedoc` likely was.

However as versions change over time it's possible for `typescript` to be hoisted out of `typedoc/node_modules` when dependencies align, like in my case.

Man... I know I've actually dealt with this sort of thing before, but I don't remember if there was a better solution than a careful and fragile (as seen by the break I experienced) aligning of dependency versions :/

**Comment by nrser** [comment]
When NPM/Yarn end up giving `typedoc` and `typedoc-plugin-biblio` two different installations of `typescript` you end up with errors during TypeScript build of `typedoc-plugin-biblio` (`tsc`) like:

```
src/plugin.ts:60:67 - error TS2345: Argument of type 'import("/Users/nrser/src/gh/nrser/typedoc-plugin-biblio/node_modules/typedoc/node_modules/typescript/lib/typescript").Symbol[]' is not assignable to parameter of type 'import("/Users/nrser/src/gh/nrser/typedoc-plugin-biblio/node_modules/typescript/lib/typescript").Symbol[]'.
```

In my fork-'n-fix I've bumped `typedoc` dep up to `^0.15.0` and `typescript` to `3.5.x`, which makes everyone happy... for now. As discussed, this is fragile. I'm pretty sure that the situation I met this issue previously was with plugin ecosystem, where it's often times essential that all plugin packages end up loading the *same* installation of a package.

I think I solved the issue in my own system by having the core package export its reference to the imported dependencies so that plugins could import that exact one, but I haven't noticed that approach in use elsewhere.

It might be possible to hack this in a more robust way by doing runtime inspection and dynamically `require`ing the correct `typescript`, but I suspect it would need to be ducking the type checker at every turn. Unlikely to look or feel good.

**Comment by lf94** [comment]
I've also run into this - probably going to just host a copy on npm with updated deps.

**Comment by lf94** [comment]
Ok, what I've actually done:

* `mv node_modules/typedoc-plugin-biblio tools/`
* `npm install --save-dev tools/typedoc-plugin-biblio`
* edit `typedoc-plugin-biblio/dist/plugin.js` to import top-level typedoc package.

And that's it.
